module.exports = {
	arrowParens: "avoid",
	bracketSameLine: false,
	bracketSpacing: true,
	embeddedLanguageFormatting: "auto",
	htmlWhitespaceSensitivity: "css",
	insertPragma: false,
	jsxSingleQuote: true,
	printWidth: 80,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	requirePragma: false,
	semi: false,
	singleQuote: false,
	trailingComma: "es5",
	useTabs: true,
	vueIndentScriptAndStyle: false,
	tabWidth: 2,
	importOrder: ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"],
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
}
